baseURL = "https://hansenglass.no"
title = "Hansen Bygg og Glasservice AS"
author = "Ole"
languageCode = "no"
DefaultContentLanguage = "no"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
timeout = 300 # 5 minutes

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

[params]

  mainSections = ['referanser']

  googleFonts = true

  googleMaps = true

  [params.logo]
    main = "img/logo/hansen-bygg-og-glasservice.png"
    alt = "Hansen Bygg og Glasservice Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Hansen Bygg og Glasservice AS"
    fullName = "Hansen Bygg og Glasservice AS"

  [params.icon]
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Hansen Bygg og Glasservice AS"
    meta_og_title = "Hansen Bygg og Glasservice AS"
    meta_og_type = "website"
    meta_og_url = "https://hansenglass.no"
    meta_og_image = "/img/logo/hansenglass.png"
    meta_og_description = "Hansen Bygg og Glasservice AS"

[menu]

  [[menu.main]]
    identifier = ""
    name = "Hjem"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tjenester"
    name = "Tjenester"
    url = "/tjenester/"
    weight = 2

  [[menu.main]]
    identifier = "referanser"
    name = "Referanser"
    url = "/referanser/"
    weight = 3

  [[menu.main]]
    identifier = "om-oss"
    name = "Om oss"
    url = "/om-oss/"
    weight = 4

  [[menu.main]]
    identifier = "kontakt-oss"
    name = "Kontakt oss"
    url = "/kontakt-oss/"
    weight = 5

  # Footer Menu

  [[menu.footer]]
    name = "E-post"
    url = "mailto:ole@byggogglass.no"
    pre = "<i class='fa-regular fa-envelope fa-lg'></i>"
      weight = 1

  [[menu.footer]]
    name = "Telefon"
    url = "tel:+4792267086"
    pre = "<i class='fa-solid fa-phone'></i>"
      weight = 2

  [[menu.footer]]
    name = "Facebook"
    url = "https://facebook.com/hansenglassogvedlikehold"
    pre = "<i class='fa-brands fa-facebook fa-lg'></i>"
      weight = 3

  [[menu.footer]]
    name = "Insta"
    url = "https://instagram.com/hansenglass.no"
    pre = "<i class='fa-brands fa-instagram fa-lg'></i>"
      weight = 4

