baseURL = "https://example.com"
title = "Hansen Glass"
author = "Ole"
languageCode = "no"
DefaultContentLanguage = "no"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

[params]

  mainSections = ['referanser']

  googleFonts = true

  [params.logo]
    main = "img/logo/hansenglass.png"
    alt = "Hansen Glass Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Hansen Glass"
    fullName = "Hansen Glass og Vedlikehold"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Hansen glass og vedlikehold"
    meta_og_title = "Hansen glass"
    meta_og_type = "website"
    meta_og_url = "https://hansenglass.no"
    meta_og_image = "/img/logo/hansenglass.png"
    meta_og_description = "Hansen glass og vedlikehold"

[menu]

  [[menu.main]]
    identifier = ""
    name = "Hjem"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "tjenester"
    name = "Tjenester"
    url = "/tjenester/"
    weight = 2

  [[menu.main]]
    identifier = "referanser"
    name = "Referanser"
    url = "/referanser/"
    weight = 3

  [[menu.main]]
    identifier = "om-oss"
    name = "Om oss"
    url = "/om-oss/"
    weight = 4

  [[menu.main]]
    identifier = "kontakt-oss"
    name = "Kontakt oss"
    url = "/kontakt-oss/"
    weight = 5

  # Footer Menu

  [[menu.footer]]
    name = "Email"
    url = "mailto:post@hansenglass.no"
    pre = "<i class='fa-regular fa-envelope fa-lg'></i>"
      weight = 1

  [[menu.footer]]
    name = "Telephone"
    url = "tel:+4712345678"
    pre = "<i class='fa-solid fa-phone'></i>"
      weight = 2

  [[menu.footer]]
    name = "Facebook"
    url = "https://facebook.com/hansenglass"
    pre = "<i class='fa-brands fa-facebook fa-lg'></i>"
      weight = 3

  [[menu.footer]]
    name = "Insta"
    url = "https://instagram.com/hansenglass"
    pre = "<i class='fa-brands fa-instagram fa-lg'></i>"
      weight = 4

  [[menu.footer]]
    name = "Twitter"
    url = "https://pinterest.com/hansenglass"
    pre = "<i class='fa-brands fa-pinterest fa-lg'></i>"
      weight = 5
