baseURL = "https://example.com"
title = "Hansen Glass"
author = "Ole"
languageCode = "no"
DefaultContentLanguage = "no"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/hansenglass.png"
    alt = "Hansen Glass Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Tella"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Hansen glass og vedlikehold"
    meta_og_title = "Hansen glass"
    meta_og_type = "website"
    meta_og_url = "https://hansenglass.no"
    meta_og_image = "/img/logo/hansenglass.png"
    meta_og_description = "Hansen glass og vedlikehold"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
